// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbpsppsrnwigcvltoflf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicHNwcHNybndpZ2N2bHRvZmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNTQxNzAsImV4cCI6MjA4NDkzMDE3MH0.T2qRwjOhAh0p-v4CtODYF8CobPJI6VFLH7W-C3EzFWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});