// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltcmomvyylmaeikmifmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Y21vbXZ5eWxtYWVpa21pZm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3NjcyODgsImV4cCI6MjA4MjM0MzI4OH0.56aws5sd2yMPWAQdI6vJvuMkUK6DRMP1XEeTnMZfZK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});